### ISSUE TITLE
future request

### ISSUE THREAD

**Issue by groni** [juangburgos/WtDesigner#1]
Looks like a good Tool, but i can't use it, i use Linux with KDE 5 and QT 5
My wish for the future, that Linux user can use it

**Comment by juangburgos** [comment]
Hi, I will soon supply Linux (Ubuntu) and Mac binaries. Stay tuned!

**Comment by groni** [comment]
Very good to hear it.
I'll be patient and wait for it

Thanks in advance, and thanks for your fast Answer

greetings
groni

2016-04-04 9:53 GMT+02:00 Juan Gonzalez Burgos notifications@github.com:

**Comment by rimongo** [comment]
Looks like great tool. Here's a patch I created to make it work in Linux.
[patch.zip](https://github.com/juangburgos/WtDesigner/files/213805/patch.zip)

**Comment by groni** [comment]
Thank you i try it

**Comment by juangburgos** [comment]
Hey guys, the development_nix branch also compiles in linux but now I am struggling to sort out all qt and wt dependencies to create a working linux package, I keep missing so files. I am improving slowly though. Any leads are appreciated. Best wishes. Juan.

**Comment by rimongo** [comment]
What are exactly the problems that you are having? I can try to help if possible

**Comment by juangburgos** [comment]
Hi, right now I am stucked with the plugins, it seems qt requires to deploy  the Qt platform plugin "xcb". I have put the relevant *.so file in "./", "./plugins" and "./plugins/platforms" with no luck, still complaining about missing *.so file. Thanks for the help guys.

**Comment by juangburgos** [comment]
Neevr mind, I think I got it working now =)

**Comment by juangburgos** [comment]
Release v.1.0.1 now runs on Linux 64 bits, binaries will be available later today,

**Comment by groni** [comment]
Thanks for it

**Comment by juangburgos** [comment]
There you go:
https://github.com/juangburgos/WtDesigner/releases
Enjoy =)

**Comment by steveschow** [comment]
Looking forward to OSX release, or 32bit windows.

**Comment by juangburgos** [comment]
OSX is my next target, but I am learning as I go, so it takes time to get it right and well tested. Will release ASAP.

**Comment by groni** [comment]
Thank you very much for it.
The WtDesigner works on Pisi Linux 64bit with KDE 5 / QT 5 very good.
I have make only the WtDesignerInstallerV.1.0.1.bin executable with KDE no Problem:
right click on the WtDesignerInstallerV.1.0.1.bin>Properties>Permissions and add a hook on "Is executable".
After it click on the WtDesignerInstallerV.1.0.1.bin and follow the Assistant .

Very good work, and many thanks to juangburgos, here a Screenshot from it

![wtdesigner](https://cloud.githubusercontent.com/assets/3329657/14999495/f672bfcc-1189-11e6-81e8-6b08fcb69af6.png)

**Comment by juangburgos** [comment]
Hey, thanks for the feedback, I can see the webpage contents are not loading, you might have to click the **Refresh** button a couple of times. Cheers.
