### ISSUE TITLE
Code for WGroupBox title not generated correctly

### ISSUE THREAD

**Issue by cls-nebadje** [juangburgos/WtDesigner#10]
Hi Juan,

WtDesigner doesn't set the title in double quotes nor does it decode from UTF8 when generating the code for WGroupBox. When entering _Balance_ the code results in

``` c++
                        groupbox_balance->setTitle(Balance);
```

Regards
Uli

**Comment by juangburgos** [comment]
Yes, thank you, I think some other user already reported that one, I will fix on next release. Cheers.
