### ISSUE TITLE
Change default template when open

### ISSUE THREAD

**Issue by mootensai** [juangburgos/WtDesigner#2]
How to change default template when open WtDesigner?

**Comment by juangburgos** [comment]
Hi, WtDesigner loads as a default project whatever it find in the "./default" path relative to the WtDesigner executable. So if you want to change it, just overwrite the "./default" path in the WtDesigner install folder to your own default template.

**Comment by mootensai** [comment]
Oh, so i have to change default.wui inside the default folder right?

**Comment by mootensai** [comment]
Do you have a documentation for Wt User Interface file XML?

**Comment by juangburgos** [comment]
Yes, you have to overwrite _everything_ in the default folder, including the .wui file indeed. Sorry, no doc about the XML nor schema yet, maybe will do it in the future.

**Comment by mootensai** [comment]
Alright then. Thank you! 

nb : 
1. Please upload more videos about witty.. about database connection & input output maybe?

**Comment by juangburgos** [comment]
Will do =)
