### ISSUE TITLE
WtDesigner failed to run due to lib boost version

### ISSUE THREAD

**Issue by YairAtInnovo** [juangburgos/WtDesigner#22]
Hi,
I have libboost-all-dev installed on my machine (version 1.58).
I have installed WtDesigner on my machine (Ubuntu 16.04.1), but when I tried to run WtDesigner is failed complaining in needs version 1.54 installed.
How can I fix this problem?

**Comment by juangburgos** [comment]
Hi,
I personally have not tested WtDesigner in Ubuntu 16.04, but form the error you are getting it would seem that you are having some library clashes. WtDesigner, or more specifically Wt, has boost as a dependency. It requires an specific version of boost to run. It would seem that your system is trying to load a different version to what Wt requires. 

WtDesigner ships with the corrrect version of boost it requires to run, but for some reason your system is trying to load the other one you have installed. What I would try is to modify the [WtDesigner.sh](https://github.com/juangburgos/WtDesigner/blob/master/src/linux_extras/WtDesigner.sh) file that must be installed wherever you have installed Wt. 

I would try to change the order in which the **LD_LIBRARY_PATH** is defined, see if that helps. I.e. change line 8 of **WtDesigner.sh**:

```bash
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$dirname
```

for:

```bash
LD_LIBRARY_PATH=$dirname:${LD_LIBRARY_PATH}
```

See if that helps. Else I wouldn't know what other thing to do.

Good luck.

**Comment by YairAtInnovo** [comment]
Hi,

I tried that, but it then complained that it could not find libsttapp-0.10 …
I managed to install it, and it looked like working, but than, the code that it generates fails to compile.


yair@yair-Linux-Laptop:~/Documents/WtDesignTest1/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yair/Documents/WtDesignTest1/build
yair@yair-Linux-Laptop:~/Documents/WtDesignTest1/build$ 
yair@yair-Linux-Laptop:~/Documents/WtDesignTest1/build$ 
yair@yair-Linux-Laptop:~/Documents/WtDesignTest1/build$ make
Scanning dependencies of target WtDesignTest1
[ 33%] Building CXX object CMakeFiles/WtDesignTest1.dir/main.o
In file included from /home/yair/Documents/WtDesignTest1/wtdesigntest1.h:6:0,
                 from /home/yair/Documents/WtDesignTest1/main.cpp:1:
/home/yair/Documents/WtDesignTest1/ui_wtdesigntest1.h: In member function ‘void Ui_WtDesignTest1::connectAllSignals()’:
/home/yair/Documents/WtDesignTest1/ui_wtdesigntest1.h:81:29: error: ‘bind’ is not a member of ‘std’
   button->clicked().connect(std::bind([=]() { text->toggleStyleClass ("hidden", !text->hasStyleClass("hidden"));
                             ^
/home/yair/Documents/WtDesignTest1/ui_wtdesigntest1.h:81:29: note: suggested alternatives:
In file included from /usr/include/boost/bind.hpp:22:0,
                 from /usr/include/boost/signals2/slot.hpp:15,
                 from /usr/include/boost/signals2/connection.hpp:23,
                 from /usr/include/boost/signals2/signal.hpp:22,
                 from /usr/include/boost/signals2.hpp:19,
                 from /usr/local/include/Wt/WObject:138,
                 from /usr/local/include/Wt/WApplication:25,
                 from /home/yair/Documents/WtDesignTest1/wtdesigntest1.h:4,
                 from /home/yair/Documents/WtDesignTest1/main.cpp:1:
/usr/include/boost/bind/bind.hpp:2016:1: note:   ‘boost::bind’
 BOOST_BIND( M T::*f, A1 a1 )
 ^
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37:0,
                 from /usr/include/boost/mpl/bind_fwd.hpp:32,
                 from /usr/include/boost/mpl/bind.hpp:23,
                 from /usr/include/boost/mpl/lambda.hpp:18,
                 from /usr/include/boost/mpl/iter_fold.hpp:20,
                 from /usr/include/boost/variant/detail/initializer.hpp:28,
                 from /usr/include/boost/variant/variant.hpp:30,
                 from /usr/include/boost/signals2/slot_base.hpp:22,
                 from /usr/include/boost/signals2/detail/tracked_objects_visitor.hpp:18,
                 from /usr/include/boost/signals2/slot.hpp:22,
                 from /usr/include/boost/signals2/connection.hpp:23,
                 from /usr/include/boost/signals2/signal.hpp:22,
                 from /usr/include/boost/signals2.hpp:19,
                 from /usr/local/include/Wt/WObject:138,
                 from /usr/local/include/Wt/WApplication:25,
                 from /home/yair/Documents/WtDesignTest1/wtdesigntest1.h:4,
                 from /home/yair/Documents/WtDesignTest1/main.cpp:1:
/usr/include/boost/mpl/aux_/preprocessed/gcc/bind_fwd.hpp:18:8: note:   ‘boost::mpl::bind’
 struct bind;
        ^
In file included from /home/yair/Documents/WtDesignTest1/wtdesigntest1.h:6:0,
                 from /home/yair/Documents/WtDesignTest1/main.cpp:1:
/home/yair/Documents/WtDesignTest1/ui_wtdesigntest1.h:81:114: warning: lambda expressions only available with -std=c++11 or -std=gnu++11
 ton->clicked().connect(std::bind([=]() { text->toggleStyleClass ("hidden", !text->hasStyleClass("hidden")); }));
                                                                                                             ^
CMakeFiles/WtDesignTest1.dir/build.make:62: recipe for target 'CMakeFiles/WtDesignTest1.dir/main.o' failed
make[2]: *** [CMakeFiles/WtDesignTest1.dir/main.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/WtDesignTest1.dir/all' failed
make[1]: *** [CMakeFiles/WtDesignTest1.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2


I tried to build WtDesigner from scratch (I have a commercial license for Qt, and I’ve been using it a lot; current version of Qt is 5.8).
However, qmake outputs an error saying it can not find webkitwidgets

Any idea how to proceed? I really like the concept of the tool, but I can’t get it to run…

Regards,
Yair

---------------------------------
Yair Raz
Innovo Concepts, Inc.
www.innovo-concepts.com
yair@innovo-concepts.com
Phone: (408) 499-7025
Fax:     (786) 257-5732
----------------------------------

**Comment by juangburgos** [comment]
Hi,

Again it seems from your errors that you do not have installed the correct Wt dependencies. To compile the project generated by WtDesigner, first I would make sure that I can compile a simple Wt hello world example from their official website and then try to build the project generated by WtSigner.

https://www.webtoolkit.eu/wt/

Now if you want to build WtDesigner form scratch, that is a different animal. I have some notes I made for myself, maybe they can help you. 

https://www.evernote.com/shard/s205/sh/cd80c0a7-3fe5-40b0-8784-dc1bd7d08639/1065e8a139699dea8c5f05df1ab21e4e

But beware I might not be able to help you further than that if you run into specific issues in your system.

If you really want to build WtDeisgner yourself, let me give you am advice. Try to do it in a clean virtual machine, this way you make sure you do not get library clashes with existing installations in your system.

best of luck

**Comment by pirx08** [comment]
I've been using WtDesigner on my Ubuntu16.04 for a few months now. Apart from a few hickups it works great for me (thanks Juan).
Here's how I installed it (also guided by Juan's personal [installation notes](https://www.evernote.com/shard/s205/sh/cd80c0a7-3fe5-40b0-8784-dc1bd7d08639/1065e8a139699dea8c5f05df1ab21e4e)):

* install required packages:
```sh
sudo aptitude install libboost-all-dev postgresql libpq-dev libpango1.0-dev libssl-dev build-essential cmake libqt5webkit5-dev
```
* download & extract [wt-3.3.5-rc2](https://sourceforge.net/projects/witty/files/wt/3.3.5/wt-3.3.5-rc2.tar.gz/download)
* build & install Wt:
```sh
cd <projects/wt-x.x.x>
mkdir build
cd build
cmake ../
make
sudo make install
sudo ldconfig
```
* get ​WtDesigner sources, configure, build & install (on Ubuntu desktop):
```sh
cd <projects>
git clone https://github.com/juangburgos/WtDesigner.git
cd WtDesigner/src/main
qmake -qt=5 -spec linux-g++
make all
ln -sv ../../bin/WtDesigner/WtDesigner WtDesigner
ln -sv ../linux_extras/WtDesigner.sh WtDesigner.sh
WTDESIGNER_PATH=`realpath ../../`
sed -r "s,\{UNKNOWN_PATH\}/WtDesigner.sh,${WTDESIGNER_PATH}/src/main/WtDesigner.sh," ../linux_extras/WtDesigner.desktop | sed -r "s,\{UNKNOWN_PATH\}/WtDesigner_logo_linux.xpm,${WTDESIGNER_PATH}/rec/WtDesigner_logo_linux.xpm," > ~/Desktop/WtDesigner.desktop
chmod +x ~/Desktop/WtDesigner.desktop
```

**Comment by juangburgos** [comment]
Thanks for sharing your solution! Lets see if it helps Yair.

**Comment by YairAtInnovo** [comment]
Hi,

I was able to build the Wt package (version 3.3.7) from scratch on my machine, and built/run all examples.
Also, I built a simple example by hand and was able to build and run by compiling it manually…

Regards,
Yair



---------------------------------
Yair Raz
Innovo Concepts, Inc.
www.innovo-concepts.com
yair@innovo-concepts.com
Phone: (408) 499-7025
Fax:     (786) 257-5732
----------------------------------

**Comment by oldbitsnbytes** [comment]
I've followed pirx08 steps. But Wt 3.3.7 and qt5 already installed and good to build WtDesign against it from qtcreator 4.3.x, I now have WtDesigner icon on my linux (Archlinux:KDE Desktop (plasma in folderview mode) and I now understand (realize) how WtDesigner is ...more than a click'n drag Designer... :) 
Thank you friends. 

 - bretzelus 
(Serge Lussier)

**Comment by YairAtInnovo** [comment]
Close
