### ISSUE TITLE
Wtdesigner problem

### ISSUE THREAD

**Issue by ghandimandel** [juangburgos/WtDesigner#26]
Hi Juan
I am a WTDESIGNER newbie.
I have loaded WtDesigner, Cmake and Wt library
I watched your "first app" video but now I'm stuck
When I try to export a saved project to Cmake, it gives me an error that it can't find the WT library files.
I have checked the paths in settings under Cmake, they are OK.
Any ideas?
![capture](https://user-images.githubusercontent.com/36946775/51586309-cd041980-1f30-11e9-84d1-5771a66fd82c.PNG)

**Comment by juangburgos** [comment]
Sorry my friend, this repo is no longer supported. But if you really want to make WtDesigner work, you must folow the youtube tutorials exactly, using the **same** software versions. I.e. same Visual Studio version, same library versions, etc.

Good luck.
