### ISSUE TITLE
Linux build instructions

### ISSUE THREAD

**Issue by cls-nebadje** [juangburgos/WtDesigner#3]
Hi Juan,

thanks a lot for this great application! I'm on 32bit Linux here (Ubuntu 14.04) and don't want to bother you with yet another binary flavour. Perhaps you can add some build instructions to the global read me - this way any interested party can build WtDesigner on its own.

Regards
Uli

**Comment by juangburgos** [comment]
Hi Uli,

Indeed is hard to keep on with binaries and stuff but in general it should be simple. You just need to put attention on having the right **versions** of the dependencies.

Dependencies:
- Qt 5.5 with QtWebkit module  (neither newer or older version will work, webkit module sometimes is shipped separatelly)
- Wt 3.3.5 (same thing here, plus its dependencies)

After you have all that just go to the `/src/main` folder of the repo and execute:

``` bash
$ qmake
$ make all
```

or alternativelly you can open the `/src/main/wtdesigner.pro`with QtCreator and build it there. 

[**HERE is a link**](https://www.evernote.com/shard/s205/sh/cd80c0a7-3fe5-40b0-8784-dc1bd7d08639/1065e8a139699dea8c5f05df1ab21e4e) to a personal note of mine for compiling and building in linux, but _do not_ guarantee that fowllowing these instructions step by step will lead to success, but it might save you some time.

Good luck and let me know how it goes.
